# Generated by Django 4.2.7 on 2023-11-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
                ('category', models.TextField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
