# Generated by Django 4.2.7 on 2023-11-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('stationary', 'stationary'), ('electronics', 'electonics'), ('networks', 'networks')], max_length=100, null=True),
        ),
    ]
