# Generated by Django 4.2.7 on 2023-12-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
                ('password', models.TextField(max_length=50, null=True)),
                ('emailaddress', models.TextField(max_length=100, null=True)),
                ('mobileno', models.TextField(max_length=25, null=True)),
                ('active', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'registratoin',
            },
        ),
    ]
